### ISSUE TITLE
Avoid using math/rand for generating passwords

### ISSUE THREAD

**Issue by DrJosh9000** [mactsouk/opensource.com#1]
Passwords are security-sensitive things, so you should heed the warning at the top of [the package documentation of math/rand](https://godoc.org/math/rand): 

> For random numbers suitable for security-sensitive work, see the crypto/rand package.

**Comment by DrJosh9000** [comment]
(I realise that crypto/rand is briefly mentioned in the opensource.com article, but since this repo is presented as demonstration code it would be great if it did the right thing.)

**Comment by mactsouk** [comment]
You are right about it. The crypto/rand package is more suitable for generating "really secure" passwords.

**Comment by mactsouk** [comment]
Added a random password generator utility named `cryptoRand.go` at that uses `crypto/rand` 😄
