### ISSUE TITLE
Can I use cp3 to make a bitstream copy?

### ISSUE THREAD

**Issue by gaurav-gogia** [mactsouk/opensource.com#2]
Hi!

I am hoping to make a bitstream copy of a device. Idea is to emulate work done by dd command. So, does this cp3 method of copying a file work the same way?

I am hoping to take /dev/sdb as input, make a bitstream copy and generate a single raw disk image file.
Please let me know if it'll be possible using cp3 or am I going to need to use some other method.

Thanks ^.^

**Comment by mactsouk** [comment]
Hello!
I am afraid that `cp3` is not suitable for copying devices such as `/dev/sdb`. It is more suitable for regular files.
